# Generated by Django 4.1.7 on 2023-02-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_categorymodel_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='category_image',
        ),
    ]
