# Generated by Django 4.1.7 on 2023-02-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_categorymodel_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='category_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
