# Generated by Django 4.1.6 on 2023-02-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_categorymodel_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=9)),
                ('product_price', models.IntegerField(blank=True)),
                ('product_count', models.IntegerField(blank=True)),
            ],
        ),
    ]
